name: Create all packages

on: [workflow_dispatch,workflow_call]

permissions: write-all

jobs:
  rpm-create:
    uses: ./.github/workflows/create-rpm-packages.yml
    secrets: inherit

  deb-create:
    uses: ./.github/workflows/create-deb-ppa-packages.yml
    secrets: inherit

  aur-create:
    uses: ./.github/workflows/create-aur-packages.yml
    secrets: inherit

  choco-create:
    uses: ./.github/workflows/create-choco-packages.yml
    secrets: inherit